=== Daedeross/maptool-script.vscode/server/src/data/_functions.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://github.com/Daedeross/maptool-script.vscode/functions",
    "title": "Functions",
    "description": "Definition of built-in functions.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "The primary name of the function. Should match the wiki title."
            },
            "aliases": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "description": {
                "type": "string"
            },
            "isTrusted": {
                "type": "boolean"
            },
            "usages": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "parameters" : {
                            "type": [ "object" ],
                            "additionalProperties":
                            {
                                "type": [ "object", "boolean" ],
                                "properties": {
                                    "type": {
                                        "oneOf": [
                                            {
                                                "type": "string",
                                                "enum": [ "number", "string", "string List", "string Property List", "JSON Array", "JSON Object" ]
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "enum": [ "number", "string", "string List", "string Property List", "JSON Array", "JSON Object" ]
                                                }
                                            }
                                        ]
                                    },
                                    "default": {
                                        "type": [ "boolean", "string", "number" ]
                                    },
                                    "description": {
                                        "type" : "string"
                                    },
                                    "isParamArray" : {
                                        "type": "boolean"
                                    }
                                }
                            }
                        },
                        "isTrusted" : {
                            "type": "boolean"
                        }
                    }
                }
            },
            "returns": {
                "type": "string"
            },
            "notes": {
                "type": "string"
            },
            "wiki": {
                "type": "string"
            }
        },
        "required": [ "name", "usages" ]
    }
}

=== Daedeross/maptool-script.vscode/server/src/data/functions.mts.json
[
    {
        "name": "abort",
        "aliases": [],
        "description": "Is used to conditionally abort the execution of a macro.",
        "usages": [
            {
                "parameters": {
                    "abrt": {
                        "type": "number",
                        "description": "`0` if the abort function should abort the macro, nonzero if it should not."
                    }
                }
            }
        ],
        "notes": "Note that only the output of the macro is discarded when the macro is aborted any changes made to macros will not be undone.",
        "wiki": "/abort"
    },
    {
        "name": "absolutevalue",
        "aliases": [
            "abs"
        ],
        "description": "Returns the absolute value of a number.",
        "usages": [
            {
                "parameters": {
                    "num": {
                        "type": "number",
                        "description": "The number to take the absolute value of."
                    }
                }
            }
        ],
        "notes": "The absolute value of a number is the number without the sign.",
        "wiki": "/absolutevalue"
    },
    {
        "name": "add",
        "aliases": [
            "sum",
            "concat"
        ],
        "description": "Retruns the sum of two or more numbers, or concatenates multiple strings together.",
        "usages": [
            {
                "parameters": {
                    "values": {
                        "type": [
                            "string",
                            "number"
                        ],
                        "isParamArray": true,
                        "description": "The numbers/strings to add/concatenate together."
                    }
                }
            }
        ],
        "notes": "If at least one argument is a string, then all non-string arguments will also be treated as strings. That is, they will be passed to the `string()` function first, then concatenated normally.",
        "wiki": "/add"
    },
    {
        "name": "addAllNPCsToInitiative",
        "aliases": [],
        "description": "Adds all **NPC** tokens on the Token layer of the current map to the initiative panel.",
        "isTrusted": true,
        "usages": [
            {
                "parameters": {}
            }
        ],
        "returns": "the number of tokens that were *added* to the initiative panel. Tokens already on the initiative panel are not counted.",
        "notes": "This function will not assign any initiative value to the tokens. You can use `setInitiative()` to set the initiative value of a token.",
        "wiki": "/addAllNPCsToInitiative"
    },
    {
        "name": "addAllPCsToInitiative",
        "aliases": [],
        "description": "Adds all **PC** tokens on the Token layer of the current map to the initiative panel.",
        "isTrusted": true,
        "usages": [
            {
                "parameters": {}
            }
        ],
        "returns": "the number of tokens that were *added* to the initiative panel. Tokens already on the initiative panel are not counted.",
        "notes": "This function will not assign any initiative value to the tokens. You can use `setInitiative()` to set the initiative value of a token.",
        "wiki": "/addAllPCsToInitiative"
    },
    {
        "name": "addAllToInitiative",
        "aliases": [],
        "description": "Adds *all* tokens on the Token layer of the current map to the initiative panel.",
        "usages": [
            {
                "parameters": {}
            }
        ],
        "returns": "the number of tokens that were *added* to the initiative panel. Tokens already on the initiative panel are not counted.",
        "notes": "This function will not assign any initiative value to the tokens. You can use `setInitiative()` to set the initiative value of a token.",
        "wiki": "/addAllToInitiative"
    },
    {
        "name": "addTableEntry",
        "aliases": [],
        "description": "Adds a new row to the specified table.",
        "isTrusted": true,
        "usages": [
            {
                "parameters": {
                    "tableName": {
                        "type": "string",
                        "description": "A string containing the name of the Table."
                    },
                    "rangeStart": {
                        "type": "number",
                        "description": "An integer indicating the lowest value that will return this row."
                    },
                    "rangeEnd": {
                        "type": "number",
                        "description": "An integer indicating the highest value that will return this row."
                    },
                    "result": {
                        "type": "string",
                        "description": "A string containing the result returned by the table() function."
                    }
                }
            },
            {
                "parameters": {
                    "tableName": {
                        "type": "string",
                        "description": "A string containing the name of the Table."
                    },
                    "rangeStart": {
                        "type": "number",
                        "description": "An integer indicating the lowest value that will return this row."
                    },
                    "rangeEnd": {
                        "type": "number",
                        "description": "An integer indicating the highest value that will return this row."
                    },
                    "result": {
                        "type": "string",
                        "description": "A string containing the result returned by the table() function."
                    },
                    "imageId": {
                        "type": "string",
                        "description": "Optional and is the asset id of an image that will be returned by the `tableImage()` function."
                    }
                }
            }
        ],
        "notes": "Adding a row to a table will not automatically change the table row value, so this should be updated to avoid possible errors (See setTableRoll() function).",
        "wiki": "/addTableEntry"
    },
    {
        "name": "addToInitiative",
        "aliases": [],
        "description": "Adds the Current Token to the initiative panel. Additional parameters allow you to specify the token and an initiative value.",
        "usages": [
            {
                "parameters": {}
            },
            {
                "parameters": {
                    "AllowDuplicates": {
                        "type": "number",
                        "description": "If false (default) then will not add the token if it is already in the initiative list. If true (1) an additional entry will be added to the initiative list (so there could be multiple initiative entries for the same token)."
                    }
                }
            },
            {
                "parameters": {
                    "AllowDuplicates": {
                        "type": "number",
                        "description": "If false (default) then will not add the token if it is already in the initiative list. If true (1) an additional entry will be added to the initiative list (so there could be multiple initiative entries for the same token)."
                    },
                    "value": {
                        "type": "number",
                        "description": "The initiative value to set. If included, the initiative will be set even if the token is already on the initiative list and duplicates are not allowed."
                    }
                }
            },
            {
                "parameters": {
                    "AllowDuplicates": {
                        "type": "number",
                        "description": "If false (default) then will not add the token if it is already in the initiative list. If true (1) an additional entry will be added to the initiative list (so there could be multiple initiative entries for the same token)."
                    },
                    "value": {
                        "type": "number",
                        "description": "The initiative value to set. If included, the initiative will be set even if the token is already on the initiative list and duplicates are not allowed."
                    },
                    "tokenRef": {
                        "type": "number",
                        "description": " Either the token id or Token Name of the token to add to the initiative. Defaults to the Current Token. "
                    }
                },
                "isTrusted": true
            },
            {
                "parameters": {
                    "AllowDuplicates": {
                        "type": "number",
                        "description": "If false (default) then will not add the token if it is already in the initiative list. If true (1) an additional entry will be added to the initiative list (so there could be multiple initiative entries for the same token)."
                    },
                    "value": {
                        "type": "number",
                        "description": "The initiative value to set. If included, the initiative will be set even if the token is already on the initiative list and duplicates are not allowed."
                    },
                    "tokenRef": {
                        "type": "number",
                        "description": " Either the token id or Token Name of the token to add to the initiative. Defaults to the Current Token. "
                    },
                    "mapname": {
                        "type": "number",
